---
:shared:
  :claims:
  - first_name
  - middle_name
  - surname
  - date_of_birth
  - date_of_birth_day
  - date_of_birth_month
  - date_of_birth_year
  - address_line_1
  - address_line_2
  - address_line_3
  - address_line_4
  - postcode
  - national_insurance_number
  - bank_sort_code
  - bank_account_number
  - building_society_roll_number
  - banking_name
  - mobile_number
  - column_to_remove_teacher_reference_number
  - email_address
  - payroll_gender
  - one_time_password
  - hmrc_bank_validation_responses
  - dqt_teacher_status
  - teacher_id_user_info
  - onelogin_credentials
  - onelogin_user_info
  - paye_reference
  - practitioner_email_address
  - provider_contact_name
  - onelogin_uid
  - onelogin_idv_first_name
  - onelogin_idv_last_name
  - onelogin_idv_full_name
  - onelogin_idv_date_of_birth
  :claim_decisions:
  - trn
  - claimant_age
  - claimant_gender
  :delayed_jobs:
  - id
  - priority
  - attempts
  - handler
  - last_error
  - run_at
  - locked_at
  - failed_at
  - locked_by
  - queue
  - created_at
  - updated_at
  - cron
  :dfe_sign_in_users:
  - given_name
  - family_name
  - email
  - session_token
  :eligible_ey_providers:
  - id
  - nursery_name
  - urn
  - local_authority_id
  - nursery_address
  - primary_key_contact_email_address
  - secondary_contact_email_address
  - created_at
  - updated_at
  :eligible_fe_providers:
  - primary_key_contact_email_address
  :schools:
  - postcode_sanitised
  :file_uploads:
  - id
  - uploaded_by_id
  - body
  - created_at
  - updated_at
  :reminders:
  - full_name
  - email_address
  - one_time_password
  :student_loans_data:
  - id
  - claim_reference
  - nino
  - full_name
  - date_of_birth
  - policy_name
  - no_of_plans_currently_repaying
  - plan_type_of_deduction
  - amount
  - created_at
  - updated_at
  :school_workforce_censuses:
  - id
  - teacher_reference_number
  - school_urn
  - totfte
  - contract_agreement_type
  - subject_description_sfr
  - general_subject_code
  - hours_taught
  - created_at
  - updated_at
  :teachers_pensions_service:
  - id
  - teacher_reference_number
  - start_date
  - end_date
  - la_urn
  - school_urn
  - employer_id
  - nino
  - created_at
  - updated_at
  - gender_digit
  :international_relocation_payments_eligibilities:
  - passport_number
  - school_headteacher_name
  :levelling_up_premium_payments_eligibilities:
  - teacher_reference_number
  :early_career_payments_eligibilities:
  - teacher_reference_number
  :student_loans_eligibilities:
  - teacher_reference_number
  :further_education_payments_eligibilities:
  - teacher_reference_number
  - verification
  :journeys_sessions:
  - answers
  :early_years_payment_eligibilities:
  - provider_email_address
  - practitioner_first_name
  - practitioner_surname
  :risk_indicators:
  - id
  - field
  - value
  - created_at
  - updated_at
