---
DFE_SIGN_IN_API_CLIENT_ID: teacherpayments
DFE_SIGN_IN_API_ENDPOINT: https://test-api.signin.education.gov.uk/
DFE_SIGN_IN_IDENTIFIER: teacherpayments
DFE_SIGN_IN_ISSUER: https://test-oidc.signin.education.gov.uk:443
DFE_SIGN_IN_REDIRECT_BASE_URL: https://test.claim-additional-teaching-payment.service.gov.uk

DFE_SIGN_IN_INTERNAL_CLIENT_ID: teacherpaymentsadmin

ONELOGIN_SIGN_IN_ISSUER: https://oidc.integration.account.gov.uk/
ONELOGIN_REDIRECT_BASE_URL: https://test.claim-additional-teaching-payment.service.gov.uk
ONELOGIN_DID_URL: https://identity.integration.account.gov.uk/.well-known/did.json
ONELOGIN_JWKS_URL: https://oidc.integration.account.gov.uk/.well-known/jwks.json

DQT_API_URL: https://test.teacher-qualifications-api.education.gov.uk/v1
DQT_BASE_URL: https://test-api-customerengagement.platform.education.gov.uk/dqt-crm/v1/

HMRC_API_BASE_URL: https://test-api.service.hmrc.gov.uk
HMRC_API_BANK_VALIDATION_ENABLED: true

ORDNANCE_SURVEY_API_BASE_URL: https://api.os.uk

SUPPRESS_DFE_ANALYTICS_INIT: true

TID_BASE_URL: https://test.claim-additional-teaching-payment.service.gov.uk/targeted-retention-incentive-payments/claim
TID_SIGN_IN_API_ENDPOINT: https://preprod.teaching-identity.education.gov.uk:433
TID_SIGN_IN_CLIENT_ID: claim
TID_SIGN_IN_ISSUER: https://preprod.teaching-identity.education.gov.uk/

GOVUK_APP_DOMAIN: ""
GOVUK_WEBSITE_ROOT: ""

SENTRY_ENVIRONMENT: "test"
